coverage:
  range: 80..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80
        threshold: 5
        base: auto
    patch:
      default:
        target: 75
        threshold: 5
        base: auto
